version: '3.8'

services:
  backend:
    build:
      context: ../project-client-invest-back-end
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    environment:
      - NODE_ENV=development

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:3333
    depends_on:
      - backend
    volumes:
      - .:/app
      - /app/node_modules